name: pkgdown

on:
  push:
    branches: [main]
    paths:
      - "**/*.R"
      - "DESCRIPTION"
      - "NAMESPACE"
      - "man/**"
      - "vignettes/**"
      - "README.md"
      - "_pkgdown.yml"
      - "pkgdown/**"
      - ".github/workflows/pkgdown.yaml"
  pull_request:
    branches: [main]
    paths:
      - "**/*.R"
      - "DESCRIPTION"
      - "NAMESPACE"
      - "man/**"
      - "vignettes/**"
      - "README.md"
      - "_pkgdown.yml"
      - "pkgdown/**"
      - ".github/workflows/pkgdown.yaml"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: pkgdown
  cancel-in-progress: true

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 1
          extra-packages: |
            any::pkgdown
            any::knitr
            any::rmarkdown
            any::kableExtra
            any::flextable
            any::lmtest
            any::sandwich
            any::margins
            any::palmerpenguins
            local::.

      - name: Configure git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Build pkgdown site
        run: pkgdown::build_site(new_process = FALSE, install = TRUE, examples = FALSE)
        shell: Rscript {0}

      - name: Deploy to gh-pages
        if: github.event_name != 'pull_request'
        run: pkgdown::deploy_to_branch(new_process = FALSE, commit_message = "Deploy pkgdown site")
        shell: Rscript {0}
